Adding methods to poll gerrit for ready-to-submit patchsets
att-comdev/jarvis-connector pull request #16
Opened 2021-03-11 17:39 UTC by DannyMassa

The patchsets are then locked with a hashtag, and sent to the jarvis-system to activate the merge-pipeline

2021-03-11 18:23 UTC, slfletch approved these changes

2021-03-12 14:32 UTC, intlabs requested changes

2021-03-12 14:32 UTC, intlabs commented on gerrit/server.go
> +	req, err := http.NewRequest("GET", "http://gerrit.jarvis.local", nil)
please dont hardcode this - we already define the gerriturl via the cli flags.

2021-03-12 14:32 UTC, intlabs commented on gerrit/server.go
> +	// TODO pull this value from flag
please fix this prior to merge - hardcoded URLs etc shouldn't end up in the connector.

2021-03-12 18:47 UTC, closed without merging